# Generated by Django 5.1.1 on 2024-10-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pdf_url', models.URLField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
